Add some debug info and convert tabs to spaces

diff --git a/subrepo b/subrepo
--- a/subrepo
+++ b/subrepo
@@ -9,25 +9,25 @@ require_work_tree
 
 debug()
 {
-	if [ -n "$debug" ]; then
-		echo "$@" >&2
-	fi
+    if [ -n "$debug" ]; then
+        echo "$@" >&2
+    fi
 }
 
 say()
 {
-	if [ -z "$quiet" ]; then
-		echo "$@" >&2
-	fi
+    if [ -z "$quiet" ]; then
+        echo "$@" >&2
+    fi
 }
 
 assert()
 {
-	if "$@"; then
-		:
-	else
-		die "assertion failed: " "$@"
-	fi
+    if "$@"; then
+        :
+    else
+        die "assertion failed: " "$@"
+    fi
 }
 
 length()
@@ -35,10 +35,19 @@ length()
     echo $#;
 }
 
+short()
+{
+    commit=$1
+
+    git rev-parse --short $commit
+}
+
 find_last_subrepo_commit()
 {
     commit="$1"
     subdir="$2"
+
+    debug "[D] CALL $FUNCNAME(commit=$(short $commit), subdir='$subdir')"
     
     git rev-list --merges --parents --topo-order $commit |
     while read rev main_parent parents; do
@@ -55,6 +64,8 @@ get_subrepo_parent()
     rev="$1"
     parents="$2"
     subdir="$3"
+
+    debug "[D] CALL $FUNCNAME(rev=$(short $rev), subdir='$subdir')"
     
     subrepo_tree=$(subtree_for_commit $rev $subdir)
     for parent in $parents; do
@@ -67,30 +78,37 @@ get_subrepo_parent()
 
 toptree_for_commit()
 {
-	commit="$1"
-	# TODO: replace with plumbing
-	git show -s --format=format:%T "$commit" -- || exit $?
+    commit="$1"
+
+    debug "[D] CALL $FUNCNAME(commit=$(short $commit), subdir='$subdir')"
+
+    # TODO: replace with plumbing
+    git show -s --format=format:%T "$commit" -- || exit $?
 }
 
 subtree_for_commit()
 {
-	commit="$1"
-	dir="$2"
+    commit="$1"
+    dir="$2"
 
-	git ls-tree "$commit" -- "$dir" |
-	while read mode type tree name; do
-		assert [ "$name" = "$dir" ]
-		assert [ "$type" = "tree" -o "$type" = "commit" ]
-		[ "$type" = "commit" ] && continue  # ignore submodules
-		echo $tree
-		break
-	done
+    debug "[D] CALL $FUNCNAME(commit=$(short $commit), dir='$dir')"
+
+    git ls-tree "$commit" -- "$dir" |
+    while read mode type tree name; do
+        assert [ "$name" = "$dir" ]
+        assert [ "$type" = "tree" -o "$type" = "commit" ]
+        [ "$type" = "commit" ] && continue  # ignore submodules
+        echo $tree
+        break
+    done
 }
 
 has_subrepo_changes()
 {
     commit="$1"
     subdir="$2"
+
+    debug "[D] CALL $FUNCNAME(commit=$(short $commit), subdir='$subdir')"
 
     ! git diff-tree --exit-code --quiet "$commit" -- "$subdir" >/dev/null
 }
@@ -100,6 +118,8 @@ make_parent_args()
     parents=$@
     result=
     
+    debug "[D] CALL $FUNCNAME(parents='$parents')"
+
     for parent in $parents; do
         result="$result -p $parent"
     done
@@ -112,25 +132,28 @@ clone_commit()
     tree="$2"
     parents="$3"
     
+    debug "[D] CALL $FUNCNAME(source_commit=$(short $source_commit), tree=$(short $tree), parents='$parents')"
+
     parent_args=$(make_parent_args $parents)
 
-	# We're going to set some environment vars here, so
-	# do it in a subshell to get rid of them safely later
-	git log -1 --pretty=format:'%an%n%ae%n%ad%n%cn%n%ce%n%cd%n%B' "$source_commit" |
-	(
-		read GIT_AUTHOR_NAME
-		read GIT_AUTHOR_EMAIL
-		read GIT_AUTHOR_DATE
-		read GIT_COMMITTER_NAME
-		read GIT_COMMITTER_EMAIL
-		read GIT_COMMITTER_DATE
-		export  GIT_AUTHOR_NAME \
-			GIT_AUTHOR_EMAIL \
-			GIT_AUTHOR_DATE \
-			GIT_COMMITTER_NAME \
-			GIT_COMMITTER_EMAIL \
-			GIT_COMMITTER_DATE
-		(echo -n "$annotate"; cat ) |
-		git commit-tree $parent_args $tree  # reads the rest of stdin
-	) || die "Can't clone commit $source_commit"
+    # We're going to set some environment vars here, so
+    # do it in a subshell to get rid of them safely later
+    git log -1 --pretty=format:'%an%n%ae%n%ad%n%cn%n%ce%n%cd%n%B' "$source_commit" |
+    (
+        read GIT_AUTHOR_NAME
+        read GIT_AUTHOR_EMAIL
+        read GIT_AUTHOR_DATE
+        read GIT_COMMITTER_NAME
+        read GIT_COMMITTER_EMAIL
+        read GIT_COMMITTER_DATE
+        export  GIT_AUTHOR_NAME \
+            GIT_AUTHOR_EMAIL \
+            GIT_AUTHOR_DATE \
+            GIT_COMMITTER_NAME \
+            GIT_COMMITTER_EMAIL \
+            GIT_COMMITTER_DATE
+        (echo -n "$annotate"; cat ) |
+        git commit-tree $parent_args $tree  # reads the rest of stdin
+    ) || die "Can't clone commit $source_commit"
 }
+
